### ISSUE TITLE
Support cython `embedSignature`

### ISSUE THREAD

**Issue by multimeric** [mkdocstrings/griffe#134]
**Is your feature request related to a problem? Please describe.**
When using cython with the `embedSignature` option, the `__doc__` of the function will have the function signature in the first line of the doc. This naturally results in confusing documentation downstream in mkdocs because the signature gets repeated and presented incorrectly.

**Describe the solution you'd like**
I propose adding a new setting to all (?) docstring parsers along the lines of `cython_embed_signature: bool`, which, if true, will strip the first line from the docstring prior to parsing, and use it as the function signature instead of however it is done now.

**Describe alternatives you've considered**
* Using `show_signature: False` improves the current documentation somewhat, but the signature is still formatted incorrectly.
  
**Additional context**
* https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#:~:text=Default%20is%20True.-,embedsignature,-(True%20/%20False)
* https://stackoverflow.com/questions/50492949/how-to-display-the-arguments-of-a-cython-function-in-the-documentation

**Comment by pawamoy** [comment]
Interesting, thanks for the request :slightly_smiling_face: 

So, we already have the `ignore_init_summary` option. I guess you'd like to have this for any function.
Additionally, you'd like to use the embedded signature instead of the inspected one... not sure if that's possible :thinking: 
At least not easily.

I'd like to see an example of such rendered signatures + docstrings, could you show us that? A screenshot of your localhost:8000 docs would be just fine.

**Comment by multimeric** [comment]
Yeah sure, it looks like this (with `show_signature = true`):

<img width="968" alt="image" src="https://user-images.githubusercontent.com/5019367/222275460-ac249c66-5622-420d-af56-b836a1b7df50.png">

**Comment by pawamoy** [comment]
Hey @multimeric, @tazend. I have looked at this again and decided to close as out of scope. Cython 3.0 seems to resolve most of the issue, leaving only `__init__` method signatures to be improved. Griffe supports introspection of objects, so frameworks that build such Python objects should do it in a way that conforms with what introspection tools expect (Python objects looking like real Python objects and providing correct metadata).

Adding an option to consider the first line of a docstring to be a signature that should be parsed again and used instead of the real signature feels a bit heavy. Docstring styles are already quite complicated to support (their specs are generally under specified), so adding more custom logic is not appealing to me :sweat_smile: 

If we ever want to be able to specify default values in docstrings, it would have to re-use Python syntax, something like:

```python
def __init__(self):
    """Summary.

    Parameters:
        param1: str | int = 0
            Description of param1.
        param2: list[Class] | None = None
            Description of param2.
    """
    ...
```

...but this should be discussed in another issue, for example in this one: https://github.com/mkdocstrings/mkdocstrings/issues/577 :slightly_smiling_face:
