### ISSUE TITLE
understand and document `typing/typing_extensions.deprecated`

### ISSUE THREAD

**Issue by samuelcolvin** [mkdocstrings/griffe#169]
**Is your feature request related to a problem? Please describe.**

it would be great if mkdocstrings could add a warning to docs when the `typing/typing_extensions.deprecated` decorator is used, see [PEP 702](https://peps.python.org/pep-0702/).

I know this pep is in draft but it's already in typing_extensions and supported by vscode.

Docs example: https://docs.pydantic.dev/dev-v2/api/main/#pydantic.main.BaseModel.copy

**Describe the solution you'd like**

It would be great if mkdocstrings added a markdown warning "Deprecated: <text from decorator>"

**Describe alternatives you've considered**

I think we'll add the warning manually ourselves for now.

**Additional context**

cc @Kludex @tpdorsey

**Comment by pawamoy** [comment]
How would you want the warning to look like? A "danger" (red) admonition named "Deprecated" with the message as body?

**Comment by tiangolo** [comment]
Ah! @pawamoy, I hadn't told you (sorry), I was talking with Jelle Zijlstra, the maintaner of typeshed (`typing`), etc. He's also the author of `@deprecated`.

Because `deprecated` overlaps with my `doc()` thing, and because it would be easier reach consensus/acceptance if the scope of my doc thing is smaller, my plan (agreeing with Jelle) was to reduce `doc()` to only documentation, and then deprecation would be done by `deprecated()`.

Currently, the `deprecated` PEP only talks about usage as a decorator, but it doesn't forbid using it in `Annotated`. It's something that could be done, and even specified in a future PEP (but could be used right away).

I haven't been able to update my doc thing (and talk to you) yet because I've been deep down the rabbit hole of the Pydantic v2 migration in FastAPI, but that was the next thing I wanted to work on.

...I'm so sorry I soft-encourage you to implement everything in my current/old version that tried to cover everything. :grimacing: 

Now the idea is to try and make my `doc()` thing a draft PEP. It could end up in `typing_extensions`. If that doesn't happen I think maybe it could be accepted in https://github.com/annotated-types/annotated-types (from @adriangb, @samuelcolvin...), that could simplify adoption and maybe your implementation (not sure).

---

Just to clarify, what Samuel is asking is only the standard usage of `@deprecated()` as a decorator.

What I'm saying is that my doc thingy will no longer have the parameter/functionality to specify that something is "deprecated", or the exceptions it raises. So, for usage as a decorator, this would replace my doc thingy (that you already implemented :pray: ).

And the other thing I'm saying is that the intention is to extend the usage of `deprecated()` a bit, and also use it in `Annotated` for parameters. That will replace that feature of my doc thingy when used in `Annotated`. I'll use that in FastAPI.

**Comment by Kludex** [comment]
Not sure about others, but the way I would like to see is the yellow box (warning) with the "Deprecated" title. The position I guess would be after the description and before the attribute/parameters table.

**Comment by tiangolo** [comment]
I actually haven't thought much about the final rendering in the docs :thinking: 

In editors I like the strikethrough, but I don't have a strong opinion in the docs.

**Comment by samuelcolvin** [comment]
> A "danger" (red) admonition named "Deprecated" with the message as body?

Sounds perfect.

**Comment by tpdorsey** [comment]
Adding a CSS class on the deprecated object might be a nice touch, enabling (optional) front end customization. Something like `doc-object-deprecated` maybe. It doesn't have to do anything by default, but nice to be able to pick up via the CSS.

**Comment by pawamoy** [comment]
First version available to sponsors :slightly_smiling_face: 
https://mkdocstrings.github.io/griffe-typing-deprecated/
