### ISSUE TITLE
temporary_visited_module requires manually running patch_ast beforehand

### ISSUE THREAD

**Issue by machow** [mkdocstrings/griffe#171]
**Describe the bug**

It looks like outside of using the pytest plugin and creating a loader--which both run `patch_ast`--running `temporary_visited_module()` will fail with a message like below.

```python
AttributeError: 'Module' object has no attribute 'kind'
```

It looks like `patch_ast` mutates attributes etc.. onto `ast` classes that the visitor needs.

I wonder if turning the AstNode methods into function might help avoid some of the trickiness of chasing down the patching / making sure it's applied before anything that needs it? E.g. something like...

```python
import ast

# note that lru_cache(maxsize=None) works for python < 3.9 compat
from functools import cache

@cache
def kind(self: ast.AST) -> str:    return self.__class__.__name__.lower()

kind(ast.parse("1 + 1"))
```

Otherwise, maybe `patch_ast()` could be run inside things like `temporary_visited_module()`?

**Comment by pawamoy** [comment]
I guess we could run `patch_ast` in the helper yes :thinking: It really runs only once, checking/using a global var, so there shouldn't be any perf hit.

The alternative is to tell every library user of Griffe to call it themselves, but I understand this is not ideal.

**Comment by pawamoy** [comment]
Actually @machow I tried your suggestion to use functions rather than patching AST classes. It led me to a rabbit hole of refactors and optimizations, and really paid off I think: the code is faster, better typed, and the lib is easier to use. So thanks! I'll push soon (and you'll be able to see the amount of changes if you're interested hehe), and if you could try the main branch then, to make sure there's no regressions, that would be great :slightly_smiling_face: I'll notify you here!
