### ISSUE TITLE
Module overrides member 

### ISSUE THREAD

**Issue by patrick91** [mkdocstrings/griffe#222]
Reproduction here: https://github.com/patrick-bug-repro/griffe-member-module

In my case I have a module with the same name as one of the function in a `__init__.py` file, it's a bit odd, but it works in python, unfortunately it looks like griffe is overriding it.

```
 .
├──  README.md
└──  strawberry
    ├──  __init__.py  # here there's a type function
    └──  type
        └──  __init__.py
```

output:

```json
{
  "strawberry": {
    "kind": "module",
    "name": "strawberry",
    "labels": [],
    "members": [
      {
        "kind": "module",
        "name": "type",
        "labels": [],
        "members": [
          {
            "kind": "function",
            "name": "hello",
            "lineno": 1,
            "endlineno": 2,
            "labels": [],
            "members": [],
            "decorators": [],
            "parameters": [],
            "returns": null
          }
        ],
        "filepath": "strawberry/type/__init__.py"
      }
    ],
    "filepath": "strawberry/__init__.py"
  }
}
```

I'd expect to see the type function inside the members there too :)

**Comment by patrick91** [comment]
This seems to be handled here: https://github.com/mkdocstrings/griffe/blob/039a702e8a4463631ef19eddb49a7941b6fedd7c/src/griffe/mixins.py#L186-L208

I'm not 100% familiar with the codebase, but I wonder if members should be come a `dict[tuple[str, kind], MemberType]` so you can have members of different kinds in the dictionary?

**Comment by pawamoy** [comment]
Thanks for the repro!

Yes, that's a known issue. It's actually a design flaw. When I designed Griffe, I centered it around the syntax to access objects: `loader.modules_collection["package.module.submodule.Class.NestedClass.attribute"]`. I failed to account for the fact that a module can have both a submodule *and* a member (imported or not) of the same name.

Instead of using (name, kind) tuples, the solution I envision is to split submodules out of the `members` dictionary, and update the syntax to support colons: `package.module.submodule` to access the submodule *or* the member of the same name when there's no such submodule (no ambiguity), and `package.module:submodule` to force access to the member and not the submodule of the same name when it exists.

As you can guess, that's quite a refactor, as there are a lot of places in the code that will need an update, so I kinda focused my energy elsewhere in the meantime :sweat_smile: But this issue is definitely in the 1.0 milestone (which exists only in my head): I will not release v1 before it is fixed.

Now if someone wants to take a stab at it, I'd gladly review a PR. The spec is simple (new `submodules` attribute in the `Object` class, support `:` in keys in the member mixins. But I think the implementation will have some traps and surprises :slightly_smiling_face:
