### ISSUE TITLE
bug: MkDocs !!! and ??? admonitions can no longer be parsed

### ISSUE THREAD

**Issue by parafoxia** [mkdocstrings/griffe#235]
### Description of the bug
Prior to v39, admonitions like the ones below can be parsed:

```
!!! note
    This is a cool note!

??? note
    This note starts collapsed.
```

However since 39.0, this error is raised instead:

```
Could not parse line '!!! note'
Could not parse line '??? note'
```

This causes these admonitions to display improperly:

<details><summary>Prior to 39</summary>
<img width="1021" alt="image" src="https://github.com/mkdocstrings/griffe/assets/43846948/2997c0cf-7516-4ead-a89c-21b387e861a5">
</details>

<details><summary>39 and after</summary>
<img width="1027" alt="image" src="https://github.com/mkdocstrings/griffe/assets/43846948/027dd95b-0184-4e6f-949a-d9545a5c5602">
</details>

I use NumpyDoc and am aware #219 introduced NumpyDoc admonitions, but sometimes !!! and ??? admonitions are more useful. I think this bug may have been caused by that PR, but I could be wrong.

### To Reproduce
Use through MkDocs, here's the repo I'm working on: https://github.com/parafoxia/analytix

Griffe is currently pinned to <39, but to reproduce the error, remove the line from `requirements/docs.txt` and run `mkdocs serve`.

### Full traceback

MkDocs logs: https://mystb.in/RecoveryWholesaleOnto

### Expected behavior

It parses the admonitions.

### Environment information
- __System__: macOS-14.2.1-arm64-arm-64bit
- __Python__: cpython 3.12.1
- __Environment variables__:
- __Installed packages__:
  - `griffe` v0.40.1

### Additional context

I believe this regression *may* have been caused by #219, but I could be wrong.

**Comment by parafoxia** [comment]
This is linked to https://github.com/parafoxia/analytix/issues/61 (pawamoy responded to that as I was writing this!).

**Comment by pawamoy** [comment]
Nice timing haha!

So, for reference (stated in the linked issue):

- recent changes to our Numpydoc parser made it so that prose after sections is not allowed anymore (this makes us more compliant with Numpydoc's official style-guide which does not explicitly allow that)
- `!!!` and `???` blocks are Markdown markup, and therefore what we call prose, and that's why these cannot be parsed after known sections such as Parameters or Returns anymore
- instead, users can take advantage of the new parser capabilities, generic admonitions:

```
!!! note
    Hello.
```

...becomes:

```
Note
----
Hello.
```

- finally, note that it is still possible to use Markdown markup in all the other places it was also supported: in section item descriptions, as well as in the non-section body of the docstring:

```
Summary.

Body. Markup still allowed here:

!!! note
    Working.

Parameters
----------
param1
    Description of param1.

    !!! warning
        Warning about param1.

param2
    etc.
```

**Comment by pawamoy** [comment]
I will close this issue but pin it for some time, in case others are impacted by the change.
