### ISSUE TITLE
feature: Numpydoc reference parsing

### ISSUE THREAD

**Issue by danielk333** [mkdocstrings/griffe#326]
### Is your feature request related to a problem? Please describe.
Numpydocs rendered with `mkdocstrings` that contain [references](https://numpydoc.readthedocs.io/en/latest/format.html#references) do not render correctly.

### Describe the solution you'd like
Im not really familiar with how `mkdocstrings` and `griffe` does its parsing, but reading the code for a few minutes it seems like `griffe` is not parsing the references into its own objects, if it did it might be easy to implement up the chain to also render the docs correctly using them.

### Describe alternatives you've considered
Just skipping references altogether and use the [See Also](https://numpydoc.readthedocs.io/en/latest/format.html#see-also) section for scientific citations

### Additional context
Tried a minimal package with one file that contains 

```python
def bar():
    """A function

    Parameters
    ----------
    velocity : float or numpy.ndarray
        Meteoroid velocity [m/s]

    Returns
    -------
    float or numpy.ndarray
        Luminosity [W]

    Notes
    -----
    Symbol definitions:

     - `I` = [W] light intensity of a meteoroid, i.e. luminous intensity; radiant intensity

    Luminosity occurs in meteors as a result of decay of excited atomic (and
    a few molecular) states following collisions between ablated meteor atoms
    and atmospheric constituents. This specific model is described in [1]_.

    .. [1] Hill et al.: High geocentric velocity meteor ablation, A&A 444 p. 615-624 (2005)

    """
    pass
```
and then parsing the docs with

```python
import griffe

my_pkg = griffe.load("my_pkg", docstring_parser="numpy")
docs = my_pkg["foo.bar"].docstring.parse()
docs[3].value.description
```

gives me the notes section in one blob with the references. I guess there are two options, griffe does the parsing or mkdocstrings-python does and im not sure which one should be it or if it should be at all!

Anyway, thanks for a really nice stack for making nice documentation, really enjoying it since i switched to this.

**Comment by pawamoy** [comment]
Hi @danielk333, thanks for the kind words and for the feature request!

So, it looks like you are confusing the docstring style (Numpydoc) and the markup. The references you mention and show in your docstring seem to use reStructuredText markup. Griffe only parses docstring styles, not markup, whether it's rST, Markdown, or anything else.

Then mkdocstrings simply cannot render your references because it expects Markdown exclusively.

So my recommendation here is that you convert your reference markup to Markdown, in which references would be called footnotes I believe.

```md
Some text[^1].

[^1]: Footnote 1.
```

Rendering footnotes depends on the Markdown extensions you enable in mkdocs.yml, of course 🙂

Does that help? I'll close as I believe there's nothing actionable for us here!

**Comment by danielk333** [comment]
Awesome, I just sed-changed all my `[x]_` to `[^x]` and `.. [x]` to `[^1]:` and added 

```yaml
markdown_extensions:
  - footnotes
```
and it worked, thanks!

Yeah all my docs were rendered with sphinx before which of course used rST references which is also probably why the numpydoc's definition on their website uses them as reference and i didn't think enough about the mix between md and rst.

Aaand now that i searched a bit more i even found the footnote that the rST directive `.. deprecated::` [was replaced](https://mkdocstrings.github.io/griffe/reference/docstrings/#fn:1) by a Markdown equivalent... ironically using a footnote i didn't notice haha.

Anyway, all sorted, thanks for the quick reply.
