### ISSUE TITLE
feature: Use `griffe check` as a conventional commit checker

### ISSUE THREAD

**Issue by szymonmaszke** [mkdocstrings/griffe#338]
## Feature

As `griffe` is able to detect breaking changes, one could use it to verify whether a correct commit type (`feat!` or `fix!` was used) (source: [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/))

An example command could go something along these lines (for [GitHub flow](https://docs.github.com/en/get-started/using-github/github-flow) like workflow with feature branches from `main`):

```shell
griffe check --against main <PACKAGE> --commit [.git/COMMIT_EDITMSG]
```

Where `--commit` loads current `commit message` akin to how [`pre-commit`](https://pre-commit.com/) works. Logic would go more or less as follows:

1. If no breaking change
2. Verify `.git/COMMIT_EDITMSG` __has no__ `feat!`/`fix!` or `BREAKING CHANGE` in the message
3. Error otherwise

Or:

1. If breaking change
2. Verify `.git/COMMIT_EDITMSG` __has__ `feat!`/`fix!` or `BREAKING CHANGE` in the message
3. Error otherwise

The idea of such inference could be potentially extended to finding whether the change should be `fix`, `feat` or `BREAKING CHANGE` (is it planned for `griffe`?), which might automate/validate whole/part of the conventional commit correctness helping devs.

## Perceived cons

- New feature IMO somewhat orthogonal to the tool itself
- If this use case grows, might be better fitting as a separate tool
- Changes/adds direction to the project itself

## Perceived pros

- Changes are relatively easy
- Feature kept close to the source itself, on which it is largely based
- Potentially higher `griffe` adoption (e.g. using `griffe` as a pre-commit hook) and IMO highly useful

## Alternatives

- Separate tool with dependency on `griffe`, let me know if this is what you prefer.
- Different subcommand altogether
- Quick bash script or submodule to obtain the goal (possible, but not too portable)

**Comment by pawamoy** [comment]
Thanks for the request @szymonmaszke :slightly_smiling_face: 

Instead of integrating logic for conventional commit checkers in Griffe, I think conventional commit checkers should be able to use Griffe (through user configuration probably).

A pre-commit hook just has to run Griffe, check the return code, and if it's not 0, then assert that the commit message contains the "breaking change" marker. I'm afraid there are two many ways to implement that, we won't be able to satisfy a lot of users if we implement a single logic in Griffe itself.

I'm still open to the idea, I'd just like to see actual examples of how Griffe is used in conventional commit checkers / pre-commit hooks before we decide whether it makes sense to integrate that in Griffe directly, somehow.

> The idea of such inference could be potentially extended to finding whether the change should be fix, feat or BREAKING CHANGE (is it planned for griffe?)

Telling if it's a breaking change is already supported of course, by checking the return code of `griffe check`. Telling apart `feat` or `fix` is probably not trivial. What if your fix exposes new API? What if your new feature doesn't (it's an internal refactor that allows new specific use-cases)? Besides, I wouldn't want to tie Griffe to a specific convention (conventional commits). Again, still open to supporting more interesting use-cases! Just need to see concrete examples first.

**Comment by szymonmaszke** [comment]
@pawamoy thank you, will get back to you with an example implementation, closing for the time being.
