### ISSUE TITLE
Support complex __all__ assignments

### ISSUE THREAD

**Issue by pawamoy** [mkdocstrings/griffe#40]
**Is your feature request related to a problem? Please describe.**
We claim to support `__all__` variables for explicit exports. But we only do when it is assigned using a list/tuple and literal strings, not when summing lists and/or adding items later, and/or

**Describe the solution you'd like**
Support more complex assignments. Starred list elements and additions at least (`+` and `+=`).

**Describe alternatives you've considered**
Stop reyling on `__all__` and always resolve implicitly.

**Additional context**
Example: https://github.com/django/django/blob/main/django/db/models/__init__.py

**Comment by tristanlatr** [comment]
Looks like it's pretty easy with `astroid` to do that. Work with `pydocspec` currently. 

The inference of the `__all__` variable: https://github.com/tristanlatr/pydocspec/blob/main/pydocspec/processor/mod_attr.py#L13-L46 (where it's called: https://github.com/tristanlatr/pydocspec/blob/main/pydocspec/astbuilder.py#L246) 

The test case: https://github.com/tristanlatr/pydocspec/blob/main/pydocspec/test/test_astbuilder.py#L435-L470

It does not understand `list.extend` and `list.append` but I think it would be pretty easy to add since it supports the augmented assigment already.
